[supervisord]
nodaemon=true

[program:backend]
command=uvicorn app:app --host 0.0.0.0 --port 5003 --reload
directory=/app/ml_backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:frontend]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr